spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.33.250:3306/blog?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: Hxf19961013.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info
    com.devin.blog: debug
  file:
    name: log/blog-dev.log